### ISSUE TITLE
C++ Parenthesis fix

### ISSUE THREAD

**Issue by Shammah** [ctf0/Seti_UX#3] opened 2015-03-11 19:04 UTC
Could you please merge in https://github.com/jesseweed/seti-syntax/commit/8e260ad269920ceda72070b75e781068688aad50 from the official repository? It fixes an annoying syntax bug in C++ :)

**Comment by LinuCC** [comment] 2015-03-12 15:37
It looks like this is a problem with the syntax-files.
Try using the C++-Syntax from the package "C++ Starting Kit" for a workaround, it does not have the annoying bug.
The problem is that many syntax-files for C++ in SublimeText define the ```meta.function-call.c++```-tag on the first parenthesis, which should not happen.
The only workaround I see is to manually override it in the theme-file for C++.
Maybe there is a better solution?

**Comment by LinuCC** [comment] 2015-03-12 15:40
Screenshot for awesomeness:
![ugly-function](https://cloud.githubusercontent.com/assets/6419353/6621354/6bb33864-c8d6-11e4-8aaa-c3119c29c6eb.png)

**Comment by ctf0** [comment] 2015-03-12 19:28
@Shammah how do i merge a package made for a total diff editor to this one ? plus unfortunately i don't use any of the `C` languages so i really cant help with what to add/edit/remove/fix so for now i believe ur only solution would be what @LinuCC have said.

@LinuCC can u send me the code u r having in the SS so i can work more on the coloring ,also if u r using a diff syntax than the one coming with ST please send me the link to it too.

**Comment by Shammah** [comment] 2015-03-12 19:31
Well, 'merge', I don't know how exactly you converted the files, but I
figured you'd know the best to take over this change as well.

Roy Stoof
Software / Firmware Developer
2M Engineering Ltd.

Phone: +31 06 11705123
Email: contact@protoman.net

2015-03-12 20:28 GMT+01:00 Muah <notifications@github.com>:

**Comment by ctf0** [comment] 2015-03-12 19:39
@Shammah i can only implement whats in the original port if the syntax on ST allow that but if it doesnt i cant do anything unless someone make a a package with enough scopes to mimic the original.

**Comment by LinuCC** [comment] 2015-03-12 21:11
Opened a pull request #4 for a workaround.

**Comment by LinuCC** [comment] 2015-03-25 17:10
Since #4 is merged, I guess we can close this issue?

**Closed** 2015-03-25 18:39 UTC
