### ISSUE TITLE
Duplicate scopes in tmTheme file?

### ISSUE THREAD

**Issue by pykong** [ctf0/Seti_UX#26] opened 2017-09-02 19:26 UTC
In preparation for the next update of our awesome theme, I decided to check for duplicate scope entries.
Indeed I myself introduced a duplication for the python import scope. While this does not negatively affect the appearance of Seti_UX, it interferes with making changes to the theme, as the latter duplicate overwrites the first one.

To programmatically clean out potential other duplicates I retrieved the list below, analyzing _the whole of the tmTheme file._ Every entry represents a scope which is present more than once throughout the theme file. 

@ctf0 could you have a look into those? Check if there is a need to clean up the tmTheme file. (Some of the items are certainly artifacts.)

**Also, it may well be ok and even intended to include a single scope multiple times - _I do not know._**

```
punctuation.definition.string.end.html -- 2
Strings -- 2
Constants -- 2
entity.name.tag.localname.xml -- 2
meta.tag.xml -- 4
punctuation.definition.string.begin.html, -- 2
SublimeLinter -- 3
source.css -- 2
text.xml -- 2
entity.name.function.python -- 3
punctuation.definition.arguments.begin.python, -- 2
meta.include.php -- 6
keyword -- 2
string.unquoted.tag-string.nunjucks -- 2
punctuation.definition.string.end.css, -- 2
keyword.control.import-export.js -- 2
string.quoted.double.xml -- 4
meta.function-call.arguments.python -- 3
meta.class.js -- 3
Storage -- 2
support.type.python -- 3
meta.tag.preprocessor.xml -- 5
text.blade -- 2
String -- 2
punctuation.definition.string.begin.xml, -- 2
keyword.other.new.php -- 2
LESS -- 2
meta.diff.range.unified -- 2
PHP: -- 8
header.find-in-files -- 2
Other -- 2
meta.class.python -- 4
meta -- 25
Bracket -- 4
string.quoted.single.single-line.python -- 2
meta.structure.dictionary.value -- 2
string.quoted.single.php -- 4
support.other.namespace.php -- 2
string.quoted.double.css -- 3
punctuation.definition.arguments.end.python -- 2
brace -- 4
meta.function-call.method.js -- 2
invalid -- 2
markup.raw, -- 2
Find -- 5
punctuation.definition.string.begin.css, -- 2
variable.function.php -- 2
entity.name.function.decorator.python -- 3
variable.assignment.coffee -- 2
support.class.exception -- 2
Variables -- 2
Dict -- 2
source -- 2
In -- 5
meta.string-contents.quoted.single.php, -- 2
Tag -- 4
constant -- 3
Coffee -- 3
Operator -- 2
meta.structure.dictionary.python -- 4
Globals -- 2
string.quoted.double.xml, -- 2
attributes.tag.jade -- 3
diff.header -- 2
Number -- 2
bold -- 3
meta.function-call.static.php -- 2
- -- 3
CSS: -- 17
plist -- 5
meta.function.decorator.python -- 3
entity.other.inherited-class.python -- 2
constant.other.inline-data.html -- 4
string.quoted.double.php -- 4
Comment -- 2
doctype -- 2
entity -- 6
GitGutter -- 5
support.type -- 2
meta.attribute-selector.css -- 2
support.function -- 5
meta.function-call.python -- 7
Quotes -- 2
punctuation.definition.inserted.diff -- 2
html -- 2
var -- 2
string.unquoted.heredoc.php -- 2
meta.attribute-with-value.id.html -- 2
string -- 10
meta.property-value.css -- 5
Text -- 2
round -- 3
meta.function.python -- 4
Match -- 2
comment -- 5
Line -- 2
string.quoted.double.single-line.python -- 3
italic -- 21
support.function.misc.css -- 2
complete_tag.jade -- 3
string.quoted -- 3
entity.name.tag.block.any.html, -- 2
punctuation.definition.string -- 2
name -- 3
string.quoted.double.single-line.python, -- 3
punctuation.definition.string.begin.php, -- 2
text.plist -- 2
punctuation -- 5
normal -- 8
variable -- 2
storage -- 2
footer.find-in-files -- 2
type -- 3
meta.property-value -- 2
Variable -- 2
source.php -- 2
Predefined -- 2
function -- 4
meta.function-call -- 2
Punctuation -- 3
Class -- 4
underline -- 2
tag -- 3
meta.selector.css -- 5
text.html.vue -- 4
meta.class.inheritance.python -- 3
source.css.less -- 2
storage.modifier -- 2
coffee -- 3
Files: -- 5
meta.item-access.python -- 2
```

**Comment by ctf0** [comment] 2017-09-02 21:26
actually u r right, there ARE duplicates & i really would like to clean that up but as i am not the familiar with how the regex works for the syntax i don't know how to minimize the footprint of the scopes.

however if you found any exact duplication in scopes, you are free to clean it up, if you even have a tool to do that "like a comparison tool maybe" , it would be even more awesome 🎉

**Comment by bfelder** [comment] 2017-09-02 21:46
@ctf0 Thanks for your feedback. 

I can and will do the cleanup for python. Yet, for other syntaxes, I lack the knowledge or time to do.
I believe it is advisable to keep this issue open. So, if more people join the development of Seti_UX they will be informed by the list of duplicates above.

Regarding the tool. I am not sure what you imagine such comparison tool will do. I have a tiny script which just lists all scopes occurring more than once in the tmTheme file. It is then a human's job to proceed from there.

**Comment by ctf0** [comment] 2017-09-02 22:22
st will only read the last copy of the scope **IF** its exactly the same, if different then it will leave it alone.

so the tool i was thinking is , simply check for the scope keys that are identical 
maybe like a loop and after processing the whole file, check each array with more than one item and remove from the top and leave the last.

does this make any sense ?

**Comment by bfelder** [comment] 2017-09-03 08:30
@ctf0 I need to judge how doable such plugin might be. As you are much more knowledgeable in these matters, could you answer the following question:

Would it in this (contrived) example below, matter at all if we just deleted the first block?
Note: The scope `punctuation.section.function.lambda.begin.python` is duplicated here. Yet, in the second block, it is found together with another scope.



             // First block
            <dict>
                <key>scope</key>
                <string>punctuation.section.function.lambda.begin.python</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#1CFF7B</string>
                </dict>
            </dict>

            // Second block
            <dict>
                <key>scope</key>
                <string>punctuation.section.function.lambda.begin.python,punctuation.separator.annotation.python</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#E12CF1</string>
                </dict>
            </dict>

**Comment by ctf0** [comment] 2017-09-03 08:54
the string key have to be exact otherwise its considered a scope restriction.

consider we want to color each scope in this example `$('abc')`
- `$`
- `()`
- `'...'`
- `abc`

so actually you will end up have some partially duplicated scopes in all 4 of them

**Comment by bfelder** [comment] 2017-09-03 09:15
@ctf0 If it is not a scope restriction, but a comma separated list of scope keys it is easily doable.
The question is: Which one to delete always the previous ones. Or in case delete the single ones, as more "thought work" has gone into combining several key scopes.

**Comment by ctf0** [comment] 2017-09-03 17:07
sorry for that, comment updated

**Comment by ctf0** [comment] 2017-09-03 19:19
the answer to your question

```bash
// before
<string>punctuation.section.function.lambda.begin.python</string>
<string>punctuation.section.function.lambda.begin.python,punctuation.separator.annotation.python</string>

// after
<string>punctuation.section.function.lambda.begin.python</string>
<string>punctuation.separator.annotation.python</string>
```

**Comment by bfelder** [comment] 2017-09-08 19:01
@ctf0 I have modified my duplicate checker to reflect what you taught me about the tmTheme syntax.
This drastically lessened a number of potential duplicates in Seti_UX to this list:

```
meta.function-call.python 
meta meta meta meta string.quoted.double.single-line.python
support.class.exception
support.other.namespace.php
keyword.other.new.php
variable.other.object.js
support.class
```
_(Of which not all were duplicates at all but mere artifacts.)_



PR stands by. Could you check whether you agree with the changes I made?

Note: One intended color change regarding python's import syntax slipped in as well. You could merge this in the same PR as well. (Half the work. ;-))

**Comment by bfelder** [comment] 2017-09-08 19:06
After the duplicate scopes have been eliminated I can begin to amend the other Python definitions.

**Comment by ctf0** [comment] 2017-09-08 21:06
plz merge the latest commit to your copy

**Comment by ctf0** [comment] 2017-09-08 21:08
also am not sure, but have you finished removing all the duplication ?

**Comment by bfelder** [comment] 2017-09-08 21:28
@ctf0 Excuse a humble question: I do not understand why I need to merge the latest commit to my copy. You mean because it is not released yet and you made additional changes?

Do you have reason to think that there are still duplicate scopes left? If so tell me. I will then be able to improve.

I am personally 90% sure all duplicates have been removed.
The duplicate checker I created to give the duplicate can be found here: [tmtheme_deduper.py](https://gist.github.com/bfelder/d9048169c629b02ece018146312d1d0f)

I just started a thread on SublimeFourm to see what other think. https://forum.sublimetext.com/t/duplicate-scope-checker-for-tmtheme-files/31148

**Comment by ctf0** [comment] 2017-09-09 00:58
its okay, and yes because of the changes made so i dont need to re-apply again after ur edits.

not entirely sure whether there are still duplicates or not, am one of those ppl that needs to check line by line but the scheme is too long and i dont have the power to go through it atm.

i saw the script previously, but not sure how exactly it works as i dont know anything about python :cry:

anyway if you are sure all is done then nothing to worry about and carry on with your next PR :trophy:

**Comment by bfelder** [comment] 2017-09-09 08:59
@ctf0 Great.

The script's usage does not require any knowledge of python at all!
You can simply run it via `python tmtheme_deduper.py path/to/my.tmTheme`.
(Should run with python2 as well.)

- The script will then iterate over the entire XML tree.
- If a node's text has the value `'scope' `then the next node's values are retrieved.
- They're `split on ','` and individually loaded into a Counter dictionary.

All keys of this Counter with a counter value `=> 2` are finally printed out.

Some false positives occur. 
Manual deletion of scopes is necessary.

**Comment by bfelder** [comment] 2017-09-13 21:23
@ctf0 Could you have another look at the duplicate issue?
Search for "entity.name.function.python meta.generic-name.python" (note: no comma here) and then again for "entity.name.function.python". The first extended scope overwrites the latter one.

**Comment by ctf0** [comment] 2017-09-13 22:27
its intended,`entity.name.function.python meta.generic-name.python` gives u more control to color this scope , instead of having a global `entity.name.function.python` scope that colors all its children the same

**Comment by ctf0** [comment] 2017-09-21 04:32
hey @pyking2 is it possible to have a script that gets all the lines with the same hex code & maybe run some operations on it **like combining them together**

am thinking of combining all the scopes that have the same `<key>settings</key>` value, it will reduce the file size drastically and will make maintenance much easier

**Comment by pyking2** [comment] 2017-09-21 07:52
@ctf0 That would be simple to do. 
Yet, I doubt that reducing size matters especially regarding how well Sublime Text handles large files sizes.

Also, maintenance would become impossible, if you just combine all scopes, no matter to which syntax they belong or how related they are, only according to their shared color value.

Ironically just yesterday I wrote a python script to extract all different hex values from the tmTheme file in order to obtain the complete color palette, I ended up with no less than **197 unique colors**!
Obviously, a color scheme requires a greater number of colors than the palettes used for web design, but 197 is far too much. We need to clean that up, too.
See: https://github.com/ctf0/Seti_UX/issues/29

Once we have reduced the number of colors, changing existing ones is just a matter of using replace all function in any editor. IMHO a custom script would not be easier to use.

I am currently exploring whether it is possible to merge the python scopes by a short program, as it would be painful to do by hand.

**Comment by ctf0** [comment] 2017-09-21 07:59
honestly it have pros and cons
> pros
 you can now find which color you a scope to be equal and add the scope to it.

> cons
the scope list will be massive especially that we cant have new line per scope.

the reason i wanted to do that because atm i want to add support for new js package & with the way am currently picky with colors and stuff its just pure agony.

regarding the colors, yes I DO have to minimize that to something sensible

**Comment by pyking2** [comment] 2017-09-21 08:04
@ctf0 The vast number of colors makes it also impossible to combine scopes.
Otherwise, it would be very simple as I said.

So, tell me what I can do exactly to help you in this regard.

**Comment by ctf0** [comment] 2017-09-21 08:11
i think i have a good idea, send me a PR with ur current progress
i will cleanup the colors with find & replace then push back.

i believe this will make it much easier for you to work with.

**Comment by pyking2** [comment] 2017-09-21 08:13
That sounds good. Just use the current PR still open.

**Comment by ctf0** [comment] 2017-09-21 08:27
can u plz check and resolve the confliction ?

**Comment by pyking2** [comment] 2017-09-21 11:01
You can clean up colors for all python as well. Set them to any value that suits you. I am going to re-edit them once I have merged all definitions. If in doubt just them to `#FFFFFF`.
At this point, it is more important to clean up colors then ending up with a polished (python) theme.

After cleanup, we should define the color palette in a separate file so that allowed colors are stated somewhere for anyone wishing to contribute to this awesome color scheme.

**Comment by ctf0** [comment] 2017-09-21 14:50
Python 3 - from Peter Varo scopes are global, it simply screwed everything up, plz only include the scopes you need, dont copy the others scheme as a whole and paste it

**Comment by pyking2** [comment] 2017-09-21 20:24
I do not know about global scopes. I thought once I removed the duplicates - which I did - there would be no interference. That is unfortunate, I really like to support **Python 3 - from Peter Varo** as it is the most popular python syntax for sublime. How can we make this work?

**Comment by ctf0** [comment] 2017-09-22 04:41
dont include the scopes that is already in seti

**Comment by ctf0** [comment] 2017-09-22 13:29
now start adding any extra scopes you want off the latest commit, also while working if you found any scope missing a color plz tell me

**Comment by ctf0** [comment] 2017-09-22 13:33
btw can you open a new ticket with all the scripts you used "with some info on how to use if possible" for ref ?

**Comment by pyking2** [comment] 2017-09-22 13:36
1. OK, I'll try.

2. I quick checked using the patterns `><` and `> <` and did find any empty brackets for foreground color, except those in commented out nodes

3. I am going to later they day. Anyway, do you got python installed, in case you want to use the scripts? What OS are you on?

**Comment by ctf0** [comment] 2017-09-22 14:05
am on mac so i believe python is already installed.

the empty `></` are for overriding prev scope declaration.

**Comment by ctf0** [comment] 2017-09-22 14:06
btw i have pushed a colors md file so its easier to find the color you want, but as am not that good with md so if you can enhance it plz do.

**Comment by ctf0** [comment] 2017-09-22 14:28
maybe we can have a script that reads the file hex colors and create the md/html on the fly like https://packagecontrol.io/packages/Huely%20Palette%20Extractor maybe ?

**Comment by pyking2** [comment] 2017-09-22 15:49
The raw file is not markdown but HTML, as it appears.
I believe it is best to just list the hex values line by line.

This is important in case one likes to programmatically work with those colors, she will not need to extract colors from the file first.

Anyone who will want to contribute will do so via Sublime and therefore can easily display colors via ColorHighlighter. Maybe we just drop a line into the README regarding this.

**Comment by ctf0** [comment] 2017-09-22 17:12
i will add an html with color rep & hex for better visualization, maybe even make it a little side project.

anyway would it be too much if i asked u to wait till i merge some colors, now that i can see better what are colors are very alike ?

**Comment by pyking2** [comment] 2017-09-22 18:25
@ctf0 We may include both an HTML for better visualization and a simple file. Both can be easily created by a script. If you tell me about the structure of HTML I can do that.

My plan is to wait anyway until you have made the changes required.

Again if you like to merge colors t reduce their total number I may do this easily.
All I need is a list of colors to be rounded to.

**Comment by ctf0** [comment] 2017-09-22 18:51
actually i just spent the last hr or so trying to merge the colors but it either looks dull or made me want to sleep, so its kept as it is and i've add the html instead, just open it in ur browser and you will get both the color and hex

**Comment by pyking2** [comment] 2017-09-22 20:54
Regarding the scripts that you want me to upload, which functions do you seek exactly?
I once uploaded the script for seeking duplicate scopes and linked it here.

Which other do you want?

**Comment by ctf0** [comment] 2017-09-23 03:24
the one that extracts the colors & the other that change the names.

btw i have an idea call scheme merger.

atm you want to add support for 3 python packages + the default that comes with st,
so instead of searching for the scopes and copy/paste them manually,
why not make a script that cross reference scope names in both scheme files and only add the new ones,
the full scope line have to match to be ignored otherwise its considered as new.
and maybe add a custom name "maybe the scheme name" above each new scope so you can track later any changes.

this way you are only left to decide what color should be added.

**Comment by pyking2** [comment] 2017-09-23 11:01
I have uploaded both scripts. Usage should be very simple. Instructions included. I have not tested on MacOS but the command line should be the same as on Linux. 
Tell me if you need anything.

HexReplace:
https://gist.github.com/pyking2/0ae113a629106220e6808d6c44db505d

HexExtract:
https://gist.github.com/pyking2/c1f148b3c8d0f54c804501a63ca6d649

**Comment by pyking2** [comment] 2017-09-23 11:04
@ctf0 Indeed I was thinking about such script to auto-merge scopes. But I am not sure how to do it.
Most likely it has to be a sublime package which extracts scopes under different syntaxes and saves them under keys for cross-reference. I do not know how to resolve an example file into different scopes though and do it in a way that allows for easy cross-referencing.

**Comment by ctf0** [comment] 2017-09-23 14:33
i dont think we need a package for that but here is what i think of

- make a script that takes 3 args "scheme 1, scheme 2, output file"
- in each scheme file search for `<key>scope</key>` and get next line `<string>.*</string>`
- now cross ref between both files results
- for unique ones, traverse up to first `<dict>` and down to second `</dict>` and copy the whole block
- paste the data into the output file with a comment between each `</dict>\n**commet-here**<dict>` with the scheme file name

on side note
in the colors md file, you will a link to a tool i created for vis colors, give it a try

**Comment by pyking2** [comment] 2017-09-23 14:37
@ctf0 Just preventing duplicate scope names is simple, it is what my [deduper](https://gist.github.com/bfelder/d9048169c629b02ece018146312d1d0f) script already does!

The problem is if the underlying language definitions differ in name but refer to the same/similar keywords/structures.

**Comment by ctf0** [comment] 2017-09-23 15:07
you mean the scope name or the `<key>name</key>` ?

what `"` ? the color hex is put right under it, so you can copy it and paste it anywhere .

initially i was planning for having a simple tool to help clear up the scheme colors as quick as possible, but maybe i would add some other options later on.

if you have some thought am all ears 👂

**Comment by pyking2** [comment] 2017-09-23 15:56
I mean the content of string:
```
<key>scope</key>
<string>keyword.control.import.python</string>
```
That scope name may differ in different syntax defintions, yet color same or similar code elements.
I.E. there is no straightforward way to merge the python definitions. Just removing duplicate scopes is not doing anything in this regard.

Regarding colors.md. Now it is great! :+1: I was able to copy it into your codepen tool and it works beautifully!

Besides the TODO list already stated in the codepen.
One great function would be to _recommend new colors_ to be included.
New color should suffice the following criteria:
- harmonize with existing color palette
- maximally differ from existing colors, to be discernable
- be visible against background color

I have no idea how to implement it though. ;-)

**Comment by pyking2** [comment] 2017-09-23 16:01
I also noted that indeed many colors in Seti_UX are indeed very similar, to the degree they are not visually discernable.

Like:
- `#ffcc01ff` and `#ffd200ff`
- `#7e99a6ff` and `#66828eff`

We may still consider merging those colors close to each other. This will be a huge cleanup of code without affecting the visual appearance of Seti at all.

**Comment by ctf0** [comment] 2017-09-23 18:23
for the scopes yes its a big downside but sadly thats the only way to support more than one package & sadly ST syntax is fucked in too many ways and it gets updated very rarely

i will try to do some cleanup today without compressing too many colors.

atm i was trying to find a way to merge 2 colors programmatically as stated in the todo, but cant find a way yet.

**Comment by pyking2** [comment] 2017-09-24 06:33
What do you want the result of a color merge to be exactly?
Can you not just _decide for one color_ and then do a **replace-all** ?

**Comment by ctf0** [comment] 2017-09-24 07:01
no, the color merging means like when u put a blue on red , or yellow on green.

what u r talking about is color replacing.

**Comment by pyking2** [comment] 2017-09-26 10:35
@ctf0 

> i will try to do some cleanup today without compressing too many colors.

Did you make progress on merging the colors?

Starting the day after tomorrow I will have the time for another attempt at merging the colors.
The guys on the discord group may help me with this.

Did you consider giving me [push access](https://stackoverflow.com/questions/14969281/git-how-to-give-people-push-access-that-needs-to-be-merged-in-by-organizers) to Seti, because this would make collaboration much easier?

I know because I co-maintain two other Sublime packages already. I would never do any major change before consulting you. For the many minor changes and iterations, we do this would make our work much more fluent.

**Comment by ctf0** [comment] 2017-09-26 11:21
sent but try to follow the updates in the last commit this way we dont overlap eachother

**Comment by pyking2** [comment] 2017-09-26 12:29
@ctf0 Thanks for your trust, Muah! 

I am going to come back to you on Thursday. I do not know how much progress I can make until then merging the python schemes. Yet, colorizing them is a step that comes after merging, so you are in no immediate hurry to minimize colors.

**Comment by ctf0** [comment] 2017-09-27 11:22
btw found a way to blend 2 colors, but not sure how to incorporate it into the pen tool yet.

**Comment by pyking2** [comment] 2017-10-08 21:25
@ctf0 I am still committed to merging the python schemes. Right now I am working on a major update for SublimeLinter. 

Your color tool is great! Especially since it is really easy to remove colors.

**Comment by pykong** [comment] 2017-10-29 19:43
@ctf0 Any update on fixing that issue with your color tool?

**Comment by ctf0** [comment] 2017-10-29 20:25
its working as b4, nothing changed.

**Comment by pykong** [comment] 2017-10-29 20:36
OK, then the removal function has never work.
<kbd>Alt</kbd> + <kbd>Click</kbd> : Remove Color

Just copies the color code to clipboard but does not remove a color from the list.

**Comment by ctf0** [comment] 2017-10-29 20:43
when removing a color, a new list will show on the side, does it show up ?

also try other keys on ur keyboard, could be any of `ctrl,option,alt` depend on how the os map the keys.

**Comment by pykong** [comment] 2017-10-29 20:46
No such list appears anywhere and I have tried with all available modifier keys.

**Comment by ctf0** [comment] 2017-10-29 23:22
i've changed it to `shift + click`, hopefully ur issue is solved now

**Comment by pykong** [comment] 2017-10-30 10:04
It does! :+1: 
Thank you for the quick fix.

But how can I get the list with updated colors?
The one on the upper left is not updated at all.

**Comment by ctf0** [comment] 2017-10-30 10:15
aaaa, actually i have made the list for the removed not the remaining, i think i should make a toggle for that.

**Comment by pykong** [comment] 2017-10-30 11:11
Ah, ok. :+1: 
Let's get back to making Seti even greater.

**Comment by pykong** [comment] 2017-11-01 22:29
I see you indeed cleaned up the scheme. Now there are about 20 colors less.
Still, many colors look much the same.
I believe it is difficult to sort them out manually without some preparing them.
Here find a list of all 145 colors currently in the theme:

https://pastebin.com/ej4PybND

Have a look at those.
You may want to remove those that look almost identical.

Just provide me with a shortened list and I will then update the `.tmTheme` file.

**Comment by ctf0** [comment] 2017-11-01 23:13
not sure what u r talking about, but i havent removed any colors yet unfortunately as am working on something else

**Comment by pykong** [comment] 2017-11-02 19:06
OK. Nevermind. 
Your color tool is great, btw!

I am busy with plugin development, big release coming.
I have Seti_UX on my radar though. There's still work to be done.

**Comment by ctf0** [comment] 2017-12-18 07:01
do we still need this ?

**Closed** 2017-12-31 13:30 UTC
Labels: enhancement, question
