### ISSUE TITLE
State color palette

### ISSUE THREAD

**Issue by pyking2** [ctf0/Seti_UX#30] opened 2017-09-21 11:03 UTC
It would be great if all allowed colors for Seti_UX would be listed in a dedicated file as their hex values.
That would make it more easy for anyone wishing to contribute and allowing for easier consistency.

**Comment by ctf0** [comment] 2017-09-21 13:08
i used to use https://packagecontrol.io/packages/Huely%20Palette%20Extractor but it doesnt work anymore

**Comment by pyking2** [comment] 2017-09-21 13:13
No worries I will take over that part once we deem the theme to be ready.

Extraction of color hex values is no problem. 
I have a script and can do this. :+1: 

When it comes to visualization, it would be best to actually display the colors.
I have not found a good application for it.

Maybe Sublime's popular ColorHighlighter will have to suffice.

**Comment by ctf0** [comment] 2017-09-21 13:16
btw do u know an app , site that round hex colors to similar hue ?

**Comment by pyking2** [comment] 2017-09-21 14:00
@ctf Ah, hand work gets tiring. ,-)

No, I do not know about such an app. There might be such an app though, yet unlikely it will work for such special case as hex colors embedded in a XML file. I thought about it:

**If you provided me with the complete color palette of Set_UX. I am going to round all colors.**

- Just post a list of hex color, as I did in the other thread. 
- One color per line. 
- Uppercase preferred (outside of web dev this is convention).

Like:

```
#FFFFFF
#FF0033
#CC66FF
...
```

**Comment by ctf0** [comment] 2017-09-21 14:29
done, check last commit, its not final as i would definitely change some to how it used to be.

**Comment by ctf0** [comment] 2017-09-21 14:32
or wait up, let me finalize it first

**Comment by ctf0** [comment] 2017-09-21 14:44
so, as much as i hate this, but i need to group the scopes according to colors b4 going any further.

the last commit will have the colors down to like 10 or 15 but i honestly just hate it, i cant stand the way the scheme looks atm.

the problem is seti is built on neon, thats why u see lots of very bright eye burning colors, but i have add lots of colors as well, and to compress them down to only 10 colors or so is simply not possible.

unless you have a better idea am sorry i cant help any further.

**Comment by pyking2** [comment] 2017-09-21 20:16
I never stated that I need no more than 10 colors. I can do any number you see fit.

**Comment by ctf0** [comment] 2017-09-22 05:11
okay, good news, found the similar colors between neon and seti using

http://www.molbiotools.com/textextractor.html
http://www.molbiotools.com/listmanipulator.html

neon have 182 color
seti have 186 color
similar 18 "exclude white/black"  color

```
#00FF00
#0AEB77
#13FFA3
#218B97
#48FFC2
#673000
#6969FA
#7DC5F9
#AA00AA
#BBFD0D
#EDBA00
#EF9975
#F6AA11
#FEF611
#FF4028
#FF6F5B
#FFA325
#FFFEF7
```

so now simply have a script that find all the above hex in seti and replace with something like `abc` so we can target it later.

plz do it on the current latest seti commit

**Comment by pyking2** [comment] 2017-09-22 12:41
Pushed the wrong file.

**Comment by ctf0** [comment] 2017-09-22 13:00
the reason for non hex code is to keep it from interfering with other.

however to make sure we dont get errors in sublime when the seti is loaded, rename it and wrap it inside a comment tag, this way it fallback to white and we still can track it with ease.

**Comment by ctf0** [comment] 2017-09-22 13:02
btw i removed `48FFC2` from list, please update ur script

**Comment by pyking2** [comment] 2017-09-22 13:02
@ctf0 I used `"#EEEEEE"` as hex code to prevent Seti theme from crashing.

**Comment by ctf0** [comment] 2017-09-22 13:03
if u really need to use a hex, then extra number at the end, this is considered as alpha channel and st will respect it

**Comment by pyking2** [comment] 2017-09-22 13:08
@ctf0 I am not sure what you exactly need or what it is you want to accomplish. I replaced all occurrences of the hex color with a unique one, so they stand out and the theme file can be further modified by you.

So you want the respective line to be commented out in addition?

Please update your color list above `#48FFC2` is still in there.

**Comment by ctf0** [comment] 2017-09-22 13:10
> similar 17 "exclude white/black/48FFC2" color

its okay, just add `00` to the end of `EEEEEE`

**Comment by pyking2** [comment] 2017-09-22 13:17
Check if the most recent PR is what you require.

**Comment by ctf0** [comment] 2017-09-22 13:26
i think all in order now and we can close this one, if you need some more colors other than the one already included you can also check https://github.com/ctf0/Seti_UX/issues/29#issuecomment-331173813

**Closed by ctf0** 2017-09-22 13:26 UTC

**Comment by ctf0** [comment] 2017-09-22 13:31
btw after all is done a file with all the color codes will be added as you suggested so everyone can use it from now on
